version: '3.3'
services:

  hpds:
    image: dbmi/pic-sure-hpds:master_43af05e
    entrypoint:  java  -Xdebug -Xrunjdwp:transport=dt_socket,address=0.0.0.0:8000,server=y,suspend=n -XX:+UseParallelGC -XX:SurvivorRatio=250 -Xms1g -Xmx6g -server -jar hpds.jar -httpPort 8080 -DCACHE_SIZE=5000 -DSMALL_TASK_THREADS=1 -DLARGE_TASK_THREADS=1 -DSMALL_JOB_LIMIT=100 -DID_BATCH_SIZE=2000
   volumes:
     - /scratch/hpds_symlink/:/opt/local/phenocube
     - /scratch/hpds_symlink/:/opt/local/hpds
     - /scratch/hpds_symlink/:/opt/local/hpds/variants
     - /scratch/hpds_symlink/:/opt/local/hpds/all
   restart: always
   environment:
     - HEAPSIZE=2048
     - CACHESIZE=500
     - SMALL_TASK_THREADS=1
     - LARGE_TASK_THREADS=1
     - SMALL_JOB_LIMIT=100
     - ID_BATCH_SIZE=50000
     - SURVIVOR_RATIO=255
   networks:
     - copdgene-hpds
   expose:
     - 8080
   ports:
     - 8080:8080

     
  wildfly:
    image: jboss/wildfly:17.0.0.Final
    volumes:
      - ${CONFIG_DIR}/wildfly/modules/system/layers/base/com/sql/:/opt/jboss/wildfly/modules/system/layers/base/com/sql/
      - ${CONFIG_DIR}/wildfly/deployments/:/opt/jboss/wildfly/standalone/deployments/
      - ${CONFIG_DIR}/wildfly/standalone.xml:/opt/jboss/wildfly/standalone/configuration/standalone.xml
    networks:
      - copdgene-hpds
    restart: always
    entrypoint: /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 --debug 0.0.0.0:8787
    expose:
      - 8787
    user: root
    depends_on:
      - copy-picsure2-war
      - copy-picsureauth-war
    ports:
      - 8081:8080
      - 9990:9990
      - 8787:8787
    env_file:
      - ${ENV_FILE}

  httpd:
    build:
      context: ./httpd
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/config/psamaui/settings/settings.json:/usr/local/apache2/htdocs/psamaui/settings/settings.json
      - ${PWD}/config/picsureui/settings/settings.json:/usr/local/apache2/htdocs/picsureui/settings/settings.json
      - ${CONFIG_DIR}/httpd/cert:/usr/local/apache2/cert
      - ${CONFIG_DIR}/httpd/static:/usr/local/apache2/htdocs/picsureui/static
    networks:
      - copdgene-hpds
    restart: always
    ports:
      - 80:80
      - 443:443

  copy-picsure2-war:
    image: dbmi/picsure2:${picsure2_version}
    user: root
    volumes:
      - ${CONFIG_DIR}/wildfly/:/opt/local/docker-config/wildfly/
    networks:
      - copdgene-hpds
    entrypoint: cp /opt/jboss/wildfly/standalone/deployments/pic-sure-api-2.war /opt/local/docker-config/wildfly/deployments/

  copy-picsureauth-war:
    image: dbmi/pic-sure-auth-services:fence-integration_bc017fa055f9
    user: root
    volumes:
      - ${CONFIG_DIR}/wildfly/:/opt/local/docker-config/wildfly/
    networks:
      - copdgene-hpds
    entrypoint: cp /opt/jboss/wildfly/standalone/deployments/pic-sure-auth-services.war /opt/local/docker-config/wildfly/deployments/

networks:
  copdgene-hpds:
